version: '3.8'

services:
  oscar:
    image: oscar_img  
    build: . 
    volumes:
      - .:/app
    ports:
      - "11434:11434"  # Expose ports if needed
    environment:
      - OLLAMA_HOST=0.0.0.0:11434

